apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: everest-monitoring
  namespace: everest-monitoring
spec:
  targetNamespaces:
  - everest-monitoring
  upgradeStrategy: Default
