apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: victoriametrics-operator
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: Manual
  name: victoriametrics-operator
  source: everest-catalog
  sourceNamespace: everest-olm
