apiVersion: batch/v1
kind: Job
metadata:
  name: everest-helm-post-install-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      containers:
        - image: docker.io/mayankshah1607/everest-helm-tools:test-4
          command: ["/everest-helm-tools"]
          args: ["run-hook", "post-install"]
          imagePullPolicy: Always
          name: hook-runner
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: everest-helm-post-install-hook
      serviceAccountName: everest-helm-post-install-hook
      terminationGracePeriodSeconds: 30
