{{- if .Values.mongodb.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: percona-server-mongodb-operator
  namespace: {{ .Release.Namespace }}
spec:
  channel: stable-v1
  installPlanApproval: Manual
  name: percona-server-mongodb-operator
  source: everest-catalog
  sourceNamespace: everest-olm
  config:
    env:
    - name: DISABLE_TELEMETRY
      {{- if $.Values.telemetry }}
      value: "true"
      {{- else }}
      value: "false"
      {{- end }}
{{- end }}
{{- if .Values.pxc.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: percona-xtradb-cluster-operator
  namespace: {{ .Release.Namespace }}
spec:
  channel: stable-v1
  installPlanApproval: Manual
  name: percona-xtradb-cluster-operator
  source: everest-catalog
  sourceNamespace: everest-olm
  config:
    env:
    - name: DISABLE_TELEMETRY
      {{- if $.Values.telemetry }}
      value: "true"
      {{- else }}
      value: "false"
      {{- end }}
{{- end }}
{{- if .Values.pg.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: percona-postgresql-operator
  namespace: {{ .Release.Namespace }}
spec:
  channel: stable-v2
  installPlanApproval: Manual
  name: percona-postgresql-operator
  source: everest-catalog
  sourceNamespace: everest-olm
  config:
    env:
    - name: DISABLE_TELEMETRY
      {{- if $.Values.telemetry }}
      value: "true"
      {{- else }}
      value: "false"
      {{- end }}
{{- end }}
