apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: everest-catalog
  namespace: {{ .Values.namespace }}
spec:
  displayName: Everest Catalog
  grpcPodConfig:
    securityContextConfig: restricted
  image: {{ .Values.everest.catalogSourceImage }}:{{ .Values.everest.version }}
  publisher: Percona
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
