{{- $psSvcName := printf "packageserver-service" }}
{{- $psSvcNameWithNS := ( printf "%s.%s" $psSvcName "everest-olm" ) }}
{{- $psFullName := ( printf "%s.svc" $psSvcNameWithNS ) }}
{{- $psAltNames := list $psSvcName $psSvcNameWithNS $psFullName }}
{{- $psCA := genCA $psSvcName 365 }}
{{- $psCert := genSignedCert $psFullName nil $psAltNames 365 $psCA }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.packages.operators.coreos.com
spec:
  caBundle: {{ b64enc $psCA.Cert }}
  group: packages.operators.coreos.com
  groupPriorityMinimum: 2000
  version: v1
  versionPriority: 800
  service:
    name: packageserver-service
    namespace: everest-olm
    port: 5443
---
apiVersion: v1
data:
  tls.crt: {{ b64enc $psCert.Cert }}
  tls.key: {{ b64enc $psCert.Key }}
kind: Secret
metadata:
  name: packageserver-service-cert
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
