apiVersion: batch/v1
kind: Job
metadata:
  name: uninstall
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.image }}
          command:
          - ./helm-tools/uninstall
          imagePullPolicy: Always
          name: uninstaller
          env:
            - name: NAMESPACES
              value: {{ range $i, $ns := .Values.namespaces }}{{ if ne $i 0 }},{{ end }}{{ $ns.name }}{{ end }},{{ .Release.Namespace }},{{ .Values.vmOperator.namespace }}
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: everest-uninstaller
      serviceAccountName: everest-uninstaller
      terminationGracePeriodSeconds: 30
