apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      everest.percona.com/managed-namespace: "true"
  upgradeStrategy: Default
