apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      everest.percona.com/namespace: ""
  upgradeStrategy: Default
