apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  channel: {{ .Values.everestOperator.channel }}
  installPlanApproval: Manual
  name: everest-operator
  source: everest-catalog
  sourceNamespace: everest-olm
  {{- if ne .Values.everestOperator.version "" }}
  startingCSV: everest-operator.v{{ .Chart.Version }}
  {{- end }}
  config:
    env:
    - name: DISABLE_TELEMETRY
      {{- if .Values.telemetry }}
      value: "true"
      {{- else }}
      value: "false"
      {{- end }}
    - name: MONITORING_NAMESPACE
      value: everest-monitoring
    - name: DB_NAMESPACES
      value: test

