apiVersion: batch/v1
kind: Job
metadata:
  name: everest-helm-pre-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
spec:
  template:
    spec:
      containers:
        - image: docker.io/mayankshah1607/everest-helm-tools:test-7
          command: ["/everest-helm-tools"]
          args: ["run-hook", "pre-delete"]
          imagePullPolicy: Always
          name: hook-runner
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: everest-helm-pre-delete-hook
      serviceAccountName: everest-helm-pre-delete-hook
      terminationGracePeriodSeconds: 30
      ttlSecondsAfterFinished: 60
