apiVersion: batch/v1
kind: Job
metadata:
  name: installplan-approver
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.image }}
          command:
          - ./helm-tools/installplan-approver
          imagePullPolicy: Always
          name: installplan-approver
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: everest-installer
      serviceAccountName: everest-installer
      terminationGracePeriodSeconds: 30
