{{- $secretName := (printf "everest-accounts") -}}
{{- $secret := (lookup "v1" "Secret" (include "everest.namespace" .) $secretName ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: everest-accounts
  namespace: {{ include  "everest.namespace" . }}
  annotations:
    insecure-password/admin: "true"
data:
  {{- if not $secret }}
  users.yaml: {{ tpl (.Files.Get "everest-admin.yaml.tpl") . | b64enc }}
  {{- else }}
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
