{{- if not (lookup "v1" "Secret" .Release.Namespace "everest-jwt" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: everest-jwt
  annotations:
    helm.sh/resource-policy: keep
data:
  id_rsa: {{ genPrivateKey "rsa" | b64enc  }}
{{- end }}
