{{- $secretName := (printf "everest-jwt") -}}
{{- if not (lookup "v1" "Secret" (include "everest.namespace" .) $secretName ) }}
apiVersion: v1
kind: Secret
metadata:
  name: everest-jwt
  namespace: {{ include  "everest.namespace" . }}
  annotations:
    helm.sh/hook: pre-install
data:
  id_rsa: {{ genPrivateKey "rsa" | b64enc  }}
{{- end }}
