apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: everest-catalog
  namespace: everest-olm
spec:
  displayName: Everest Catalog
  grpcPodConfig:
    securityContextConfig: restricted
  image: {{ .Values.olm.catalogSourceImage }}:{{ .Chart.Version }}
  publisher: Percona
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
